#!/bin/bash
transmit_cnt=0


#/*----------------------------------------------------------------------*/
#/* main
#/*----------------------------------------------------------------------*/

echo "erayconfig s2 t 1 0" | timeout 3 nc -u -q 2 -p 53000 10.42.0.146 53002
sleep 1
echo "erayconfig s2 r 2 0" | timeout 3 nc -u -q 2 -p 53000 10.42.0.146 53002
sleep 1
echo "setudpip 10 42 0 28" | timeout 3 nc -u -q 2 -p 53000 10.42.0.146 53002
sleep 1
./udp_server &
sleep 3
while true; do
    transmit_cnt=`expr $transmit_cnt +  1`
    echo $transmit_cnt
    ./udp_client_eray_s2 10.42.0.146
    sleep 10
done